### ISSUE TITLE
Allow advanced cluster backup configuration

### ISSUE THREAD

**Issue by jasonmimick** [jasonmimick/atlas-osb#26]
allow for plans to update certain backup configuration changes.
Maps to Manulife - Use case 7:   As a user I should be able to configure PIT for my cluster (Sprint 3/4?)

See:
https://docs.atlas.mongodb.com/backup/cloud-backup/overview/

**Comment by vasilevp** [comment]
What works already:
```yml
cluster:
  ...
  providerBackupEnabled: true
  pitEnabled: true
```

What does not, but is supported by the Atlas client:
- Managing backup schedule

We should be able to add this in a similar fashion we did with Project creation. A new [CloudProviderSnapshotBackupPolicy](https://github.com/mongodb/go-client-mongodb-atlas/blob/7f72d26915c748762bdcf3f704f8d212862309be/mongodbatlas/cloud_provider_snapshot_backup_policies.go#L28) field in `Plan` should do the trick - most of the logic is already there

**Comment by jasonmimick** [comment]
Ok, so will it be like this in general:

For a plan,
```yaml
project:
  name:
...
cluster:
  name:
  ...
cloudProviderSnapshotBackupPolicy:
  name:
  ...
```
This should be ok, but we need to handle multiple CloudProviderSnapshotBackupPolicy's (and multiple NetworkPeering, etc, for all resources like this). 
Checking over in the go client though, seems there is only `Update` for one policy, so if we document properly we can maybe not deal with multiple backup policies. https://github.com/mongodb/go-client-mongodb-atlas/blob/7f72d26915c748762bdcf3f704f8d212862309be/mongodbatlas/cloud_provider_snapshot_backup_policies.go#L81
